apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: example-token-refresher
    app.kubernetes.io/name: token-refresher
    app.kubernetes.io/version: master-2021-03-05-b34376b
  name: example-token-refresher
  namespace: observatroium
spec:
  endpoints:
  - port: internal
  selector:
    matchLabels:
      app.kubernetes.io/instance: example-token-refresher
      app.kubernetes.io/name: token-refresher
